#JWT Configuration
jwt.secret=${JWT_SECRET:4f4d8f5c9c8b8fd4f7f0d0f4a72fd652e6e8d0ef34e77f5b76f4e22fb4e945bd}
jwt.access-expiration-minutes=15
jwt.refresh-expiration-days=7

# DataSource Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/todo_app_db
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.default_schema=todo_app_schema
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.javax.persistence.schema-generation.scripts.action=none
spring.jpa.generate-ddl=false

# Flyway Configuration
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
spring.flyway.schemas=todo_app_schema
spring.flyway.create-schemas=true
spring.flyway.validate-on-migrate=true
spring.flyway.driver-class-name=org.postgresql.Driver
spring.flyway.url=jdbc:postgresql://localhost:5432/todo_app_db
spring.flyway.user=postgres
spring.flyway.password=1234

# LDAP Configuration
spring.ldap.urls=ldap://localhost:389
spring.ldap.base=dc=example,dc=com
spring.ldap.username=cn=admin,dc=example,dc=com
spring.ldap.password=admin
spring.ldap.group-search-base=ou=groups
spring.ldap.group-search-filter=(memberUid={1})
